name: Bug Report
description: Create a bug report to help us improve.
labels: [ "status: triage", "type: bug: unconfirmed" ]
body:
  - type: markdown
    attributes:
      value: |
        Please do **not** use the 'Bug Report' template for questions, instead ask in our [Discord Server](https://discord.hypera.dev/)
  - type: checkboxes
    attributes:
      label: Confirmation
      description: Please confirm that you have done the following before creating this issue.
      options:
        - label: I have checked for similar issues.
          required: true
        - label: I using the latest version of Chameleon.
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is.
      placeholder: When I ..., ... happens.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
      placeholder: Chameleon should have ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: Provide example code that caused the bug.
      placeholder: "BukkitChameleon chameleon = BukkitChameleon.create(...);"
      render: Java
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception
      description: If an exception was printed, please provide it here.
      placeholder: "java.lang.NullPointerException: null"
      render: exception
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide information about your operating environment here.
        Make sure to include your operating system name and version, the platform(s) the bug occurs on and the version of the platform(s).
      value: |
        Operating System: <!-- e.g. Windows 11 or Ubuntu 22.04 -->
        Platform(s): <!-- e.g. Bukkit (Spigot) 1.19.1, Velocity 3.1.0 -->
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Please provide any additional information that may improve the chance of us being able to reproduce and fix this bug.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false