name: Feature Request
description: Create a feature request to suggest a feature that we can add.
labels: [ "status: enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Please do **not** use the 'Feature Request' template for questions, instead ask in our [Discord Server](https://discord.hypera.dev/)
  - type: checkboxes
    attributes:
      label: Confirmation
      description: Please confirm that you have done the following before creating this issue.
      options:
        - label: I have checked for similar issues.
          required: true
  - type: textarea
    attributes:
      label: Problem
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Please provide a clear and concise description of what you suggest a solution to this problem would be.
      placeholder: It would be helpful if Chameleon could ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Please provide any additional information about this feature request.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
