name: "Build"
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

env:
  JAVA_VERSION: 17

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3

      - name: "Set up Java ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"

      - name: "Gradle build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "build"