# GitHub Action workflow to run CodeQL.
name: "Gradle"
on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '25 6 * * 5'

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

env:
  JAVA_VERSION: 18

jobs:
  build:
    name: "Build"
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: "ubuntu-latest"
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ "java" ]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v2
        with:
          languages: "${{ matrix.language }}"

      - name: "Set up JDK ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"

      - name: "Build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "build"

      - name: "Upload reports"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "${{ runner.os }}-test-reports"
          retention-days: 7
          if-no-files-found: ignore
          path: |
            **/build/reports/tests/test/
            **/build/reports/checkstyle/
            **/build/reports/jacoco/

      - name: "Perform CodeQL Analysis"
        uses: github/codeql-action/analyze@v2
