# GitHub Actions workflow to build the project with Gradle.
name: "Gradle"
on: [push, pull_request]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

env:
  JAVA_VERSION: 18

jobs:
  build:
    name: "Build"
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"

    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Java ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"

      - name: "Gradle build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "build"

      - name: "Upload reports"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "${{ runner.os }}-test-reports"
          retention-days: 7
          if-no-files-found: ignore
          path: |
            **/build/reports/tests/test/
            **/build/reports/checkstyle/