# GitHub Actions workflow to run Gradle tasks.
name: "Gradle"
on:
  push:
    branches: [ "main", "releases/**" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: "gradle-${{ github.event.number || github.ref }}"
  cancel-in-progress: "${{ github.event.action != 'merge_group' }}"

jobs:
  validate:
    name: "Validate"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1

  build:
    name: "Build"
    runs-on: "${{ matrix.os }}"
    needs: ["validate"]
    permissions:
      contents: read
    strategy:
      matrix:
        java: [17] # Use latest LTS
        os: ["ubuntu-latest"]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          java-version: "${{ matrix.java }}"
          distribution: "temurin" # Adoptium

      - name: "Build"
        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2
        with:
          arguments: "build"

      - name: "Upload reports"
        if: always()
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: "${{ runner.os }}-test-reports"
          retention-days: 7
          if-no-files-found: ignore
          path: |
            **/build/reports/tests/test/
            **/build/reports/checkstyle/
            **/build/reports/jacoco/

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          fail_ci_if_error: false
