# GitHub Actions workflow to build a Gradle project.
name: "Gradle"
on:
  push:
    branches: [ "main", "releases/**" ]
    tags-ignore: ["**"]
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:
  build:
    uses: HyperaDev/actions/.github/workflows/gradle-build.yml@main
    with:
      java_version: 17
