# GitHub Actions workflow to run Gradle tasks.
name: "Gradle"
on:
  push:
    branches: [ "main", "releases/**" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: "gradle-${{ github.event.number || github.ref }}"
  cancel-in-progress: "${{ github.event.action != 'merge_group' }}"

jobs:
  validate:
    name: "Validate"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1

  build:
    name: "Build"
    runs-on: "${{ matrix.os }}"
    needs: ["validate"]
    permissions:
      contents: read
    strategy:
      matrix:
        java: [17] # Use latest LTS
        os: ["ubuntu-latest"]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.java }}"
          distribution: "temurin" # Adoptium

      - name: "Build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "build"

      - name: "Upload reports"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "${{ runner.os }}-test-reports"
          retention-days: 7
          if-no-files-found: ignore
          path: |
            **/build/reports/tests/test/
            **/build/reports/checkstyle/
            **/build/reports/jacoco/

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
