name: Pre-release

on:
  push:
    branches: [master]

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Cache Maven Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2
          key: ubuntu-latest-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-m2
      - name: Install with Maven
        run: mvn install
      - name: Build with Maven
        run: mvn clean package
      - name: Create prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.md
            core/target/*-SNAPSHOT.jar
            platform-bungeecord/target/*-SNAPSHOT.jar
            platform-spigot/target/*-SNAPSHOT.jar
            platform-velocity/target/*-SNAPSHOT.jar
