name: "Publish"
on:
  push:
    branches: [ "main" ]

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

env:
  JAVA_VERSION: 18

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up JDK ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"

      - name: "Determine version"
        run: |
          echo "VERSION=$(grep -oP '(?<=version = \").*(?=\")' build.gradle.kts)" >> $GITHUB_ENV

      - name: "Import GPG key"
        uses: crazy-max/ghaction-import-gpg@d6f3f49f3345e29369fe57596a3ca8f94c4d2ca7 # v5.4.0
        with:
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"

      - name: "Gradle publish"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "publish"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_hyperaReleasesUsername: "${{ secrets.HYPERA_RELEASES_USERNAME }}"
          ORG_GRADLE_PROJECT_hyperaReleasesPassword: "${{ secrets.HYPERA_RELEASES_PASSWORD }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsUsername: "${{ secrets.HYPERA_SNAPSHOTS_USERNAME }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsPassword: "${{ secrets.HYPERA_SNAPSHOTS_PASSWORD }}"

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          updateOnlyUnreleased: true
          generateReleaseNotes: true
          name: "Chameleon v${{ env.VERSION }}"
          prerelease: "${{ endsWith(env.VERSION, 'SNAPSHOT') }}"
          tag: "${{ env.VERSION }}"
