# GitHub Actions workflow to automatically create releases and publish to our maven repository.
name: "Publish"
on:
  push:
    branches: [ "main" ]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

env:
  JAVA_VERSION: 17

jobs:
  publish:
    name: "Publish"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Set up Java ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"

      - name: "Determine version"
        run: |
          echo "VERSION=$(./gradlew properties | awk '/^version:/ { print $2; }')" >> $GITHUB_ENV

      - name: "Create release"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.VERSION }}"
          prerelease: "${{ endsWith(env.VERSION, 'SNAPSHOT') }}"
          title: "Chameleon v${{ env.VERSION }}"

      - name: "Import GPG key"
        uses: crazy-max/ghaction-import-gpg@v5.0.0
        with:
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"

      - name: "Publish"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "publish"
        env:
          ORG_GRADLE_PROJECT_hyperaReleasesUsername: "${{ secrets.HYPERA_RELEASES_USERNAME }}"
          ORG_GRADLE_PROJECT_hyperaReleasesPassword: "${{ secrets.HYPERA_RELEASES_PASSWORD }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsUsername: "${{ secrets.HYPERA_SNAPSHOTS_USERNAME }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsPassword: "${{ secrets.HYPERA_SNAPSHOTS_PASSWORD }}"