# GitHub Actions workflow to publish releases.
# Releases are published from the 'releases/<major>' branches.
name: "Release"
on:
  push:
    branches: [ "releases/**" ]

jobs:
  release:
    uses: HyperaDev/actions/workflows/gradle-release.yml@main
    secrets:
      HYPERA_SIGNING_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
      HYPERA_SIGNING_PASSWORD: "${{ secrets.GPG_PASSPHRASE }}"
      HYPERA_RELEASES_USERNAME: "${{ secrets.HYPERA_RELEASES_USERNAME }}"
      HYPERA_RELEASES_PASSWORD: "${{ secrets.HYPERA_RELEASES_PASSWORD }}"
      SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
      SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
    with:
      project_name: "Chameleon"
      java_version: 17
      release_maven_central: true
