# GitHub Actions workflow to publish releases.
# Releases are published from the 'releases/<major>' branches.
name: "Gradle"
on:
  push:
    branches: [ "releases/**" ]

jobs:
  release:
    name: "Release"
    uses: HyperaDev/actions/.github/workflows/gradle-release.yml@main
    with:
      project_name: "Chameleon"
      java_version: "21"
      release_maven_central: true
    secrets:
      HYPERA_SIGNING_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
      HYPERA_SIGNING_PASSWORD: "${{ secrets.GPG_PASSPHRASE }}"
      HYPERA_RELEASES_USERNAME: "${{ secrets.HYPERA_RELEASES_USERNAME }}"
      HYPERA_RELEASES_PASSWORD: "${{ secrets.HYPERA_RELEASES_PASSWORD }}"
      SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
      SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
      GITHUB_RELEASE_TOKEN: "${{ secrets.HYPERA_BOT_TOKEN }}"
